// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_8_fnSz5YGOhbxovecy7kXYtE3HYG3E',
    appId: '1:486169088209:web:00573246cc620c26fbf5f0',
    messagingSenderId: '486169088209',
    projectId: 'testing-api-c2721',
    authDomain: 'testing-api-c2721.firebaseapp.com',
    storageBucket: 'testing-api-c2721.appspot.com',
    measurementId: 'G-QX4MN1Z1F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82HHpNw70oIhhPijaQatSQnquixRFju0',
    appId: '1:486169088209:android:1bf37aea5e7ed60ffbf5f0',
    messagingSenderId: '486169088209',
    projectId: 'testing-api-c2721',
    storageBucket: 'testing-api-c2721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUQ8xkrZskRipQs7Z18nvTysDnM_qOmbE',
    appId: '1:486169088209:ios:ffd37a911bbc5150fbf5f0',
    messagingSenderId: '486169088209',
    projectId: 'testing-api-c2721',
    storageBucket: 'testing-api-c2721.appspot.com',
    androidClientId: '486169088209-c6pgnrqqskib8bjg3m1cjlj5lt0o7m7j.apps.googleusercontent.com',
    iosClientId: '486169088209-gafqeh88aktpjtbvmnfi700bdp5l4rbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingApi2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUQ8xkrZskRipQs7Z18nvTysDnM_qOmbE',
    appId: '1:486169088209:ios:ffd37a911bbc5150fbf5f0',
    messagingSenderId: '486169088209',
    projectId: 'testing-api-c2721',
    storageBucket: 'testing-api-c2721.appspot.com',
    androidClientId: '486169088209-c6pgnrqqskib8bjg3m1cjlj5lt0o7m7j.apps.googleusercontent.com',
    iosClientId: '486169088209-gafqeh88aktpjtbvmnfi700bdp5l4rbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingApi2',
  );
}
